import Vue from 'vue'
import 'element-ui/lib/theme-chalk/base.css'
import CollapseTransition from 'element-ui/lib/transitions/collapse-transition'
import { Icon, Calendar, Image, Progress, Input, Tabs, TabPane, Tag, Menu, Submenu, MenuItem, MenuItemGroup, Button, Table, TableColumn, Pagination, Dialog, Select, Option, Container, Header, Main, Footer, Aside, Drawer, Avatar, Row, Col, Card, Divider, Dropdown, DropdownMenu, DropdownItem } from 'element-ui'

Vue.component(CollapseTransition.name, CollapseTransition)
Vue.use(Button)
Vue.use(Table)
Vue.use(Dialog)
Vue.use(Pagination)
Vue.use(Select)
Vue.use(Option)
Vue.use(TableColumn)
Vue.use(Container)
Vue.use(Footer)
Vue.use(Header)
Vue.use(Main)
Vue.use(Aside)
Vue.use(Drawer)
Vue.use(Avatar)
Vue.use(Row)
Vue.use(Col)
Vue.use(Card)
Vue.use(Divider)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Tag)
Vue.use(Input)
Vue.use(Progress)
Vue.use(Image)
Vue.use(Calendar)
Vue.use(Icon)
